Fix conversion to float in cripts/Lulu.hpp
Without this fix, the following compile error occurred:
```
/usr/sbin/ccache /usr/sbin/c++ -DDEBUG -DFMT_SHARED -DOPENSSL_API_COMPAT=10002 -DOPENSSL_IS_OPENSSL3 -DPACKAGE_NAME="\"Apache Traffic Server\"" -DPACKAGE_VERSION=\"10.1.0\" -D_DEBUG -Dcripts_EXPORTS -Dlinux -I/home/jenkins/trafficserver/include -I/home/jenkins/trafficserver/build/include -I/home/jenkins/trafficserver/lib/swoc/include -isystem /opt/openssl-quic/include -pthread -g -std=c++20 -fPIC -DENABLE_SYSTEMTAP_PROBES -Wno-invalid-offsetof -pipe -Wall -Wextra -Wno-noexcept-type -Wsuggest-override -Wno-vla-extension -fno-strict-aliasing -Wno-format-truncation -O3 -Wformat=2 -Wconversion -Wimplicit-fallthrough -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS -fstack-clash-protection -fstack-protector-strong -fstrict-flex-arrays=3 -Wtrampolines -Werror -MD -MT src/cripts/CMakeFiles/cripts.dir/Bundles/LogsMetrics.cc.o -MF src/cripts/CMakeFiles/cripts.dir/Bundles/LogsMetrics.cc.o.d -o src/cripts/CMakeFiles/cripts.dir/Bundles/LogsMetrics.cc.o -c /home/jenkins/trafficserver/src/cripts/Bundles/LogsMetrics.cc
In file included from /home/jenkins/trafficserver/src/cripts/Bundles/LogsMetrics.cc:19:
/home/jenkins/trafficserver/include/cripts/Lulu.hpp: In member function ‘cripts::string::operator float() const’:
/home/jenkins/trafficserver/include/cripts/Lulu.hpp:374:44: error: conversion from ‘double’ to ‘float’ may change value [-Werror=float-conversion]
  374 |   operator float() const { return std::stod(*this); }
      |                                   ~~~~~~~~~^~~~~~~
```