Stop including concepts header since it is not found on Ubuntu CI environment
```
/usr/bin/ccache /usr/lib/llvm-12/bin/clang++ -DDEBUG -DPACKAGE_NAME="\"Apache Traffic Server\"" -DPACKAGE_VERSION=\"10.1.0\" -D_DEBUG -Dlinux -I/home/jenkins/workspace/Github_Builds/ubuntu/src/include -I/home/jenkins/workspace/Github_Builds/ubuntu/src/build/include -I/home/jenkins/workspace/Github_Builds/ubuntu/src/lib/swoc/include -I/home/jenkins/workspace/Github_Builds/ubuntu/src/lib/yamlcpp/include -isystem /home/jenkins/workspace/Github_Builds/ubuntu/src/lib/systemtap -D_FORTIFY_SOURCE=2 -fPIE -fstack-protector -pthread -g -std=c++20 -Wno-invalid-offsetof -pipe -Wall -Wextra -Wno-noexcept-type -Wsuggest-override -Wno-vla-extension -fno-strict-aliasing -mcx16 -Werror -MD -MT src/records/CMakeFiles/records.dir/P_RecCore.cc.o -MF src/records/CMakeFiles/records.dir/P_RecCore.cc.o.d -o src/records/CMakeFiles/records.dir/P_RecCore.cc.o -c /home/jenkins/workspace/Github_Builds/ubuntu/src/src/records/P_RecCore.cc
In file included from /home/jenkins/workspace/Github_Builds/ubuntu/src/src/records/P_RecCore.cc:32:
In file included from /home/jenkins/workspace/Github_Builds/ubuntu/src/src/records/P_RecCore.h:30:
/home/jenkins/workspace/Github_Builds/ubuntu/src/include/records/RecCore.h:26:10: fatal error: 'concepts' file not found
         ^~~~~~~~~~
1 error generated.
```