Install rustup instead of cargo to use a newer version of rustc
This is needed to avoid the following error while building the Cloudflare quiche library:
error: package `serde_with v3.18.0` cannot be built because it requires rustc 1.88 or newer, while the currently active rustc version is 1.75.0